# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rDvDdhYHywvjU1Ekg_l_hD9kG7WEGVaV
"""

import random
number = random.randint(1, 10)

player_name = input("Hello, what is your name? ")
number_of_guesses = 0
print('Vamos brincar com você, eu vou pensar um número entre 1 e 10 aí você vai adivinhar, tá bom? Não se esqueça! Você tem apenas 3 chances, então adivinhe:'.format(player_name))

while number_of_guesses < 3:
    guess = int(input())
    number_of_guesses += 1
    if guess < number:
        print('Sua estimativa é muito baixa, suba um pouco!')
    if guess > number:
        print('Sua estimativa é muito alta, desça um pouco!')
    if guess == number:
        break
if guess == number:
    print( 'Parabéns {}, você adivinhou o número em {} tentativos!'.format(player_name, number_of_guesses))
else:
    print('O número era {}.'.format(number))